# Generated by Django 5.1.5 on 2025-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_templates',
            name='image1',
            field=models.ImageField(upload_to='Uploads/'),
        ),
        migrations.AlterField(
            model_name='upload_templates',
            name='image2',
            field=models.ImageField(upload_to='Uploads/'),
        ),
        migrations.AlterField(
            model_name='upload_templates',
            name='image3',
            field=models.ImageField(upload_to='Uploads/'),
        ),
    ]
