# Generated by Django 5.1.5 on 2025-02-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed_back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User_Reg',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.IntegerField()),
                ('hips', models.IntegerField()),
                ('bust', models.IntegerField()),
                ('chestgirth', models.IntegerField()),
                ('neck', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('sleeve', models.IntegerField()),
                ('bicep', models.IntegerField()),
                ('wrist', models.IntegerField()),
                ('back_waist_length', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('make_sts', models.IntegerField(default=0)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('waist', models.IntegerField()),
                ('hips', models.IntegerField()),
                ('bust', models.IntegerField()),
                ('chestgirth', models.IntegerField()),
                ('neck', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('sleeve', models.IntegerField()),
                ('bicep', models.IntegerField()),
                ('wrist', models.IntegerField()),
                ('back_waist_length', models.IntegerField()),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.upload_details')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_reg')),
            ],
        ),
    ]
