# Generated by Django 5.0.1 on 2025-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
