# Generated by Django 5.0.1 on 2025-03-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_upload_templates_image1_and_more'),
        ('user', '0004_alter_orderstatus_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.addi_staff'),
        ),
    ]
