# Generated by Django 5.0.1 on 2025-03-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('user', '0005_orderstatus_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff_reg'),
        ),
    ]
